name: yaurora
description:  💙 ublue-os/aurora-dx the way I like it 

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/faramirza/gdu/repo/fedora-%OS_VERSION%/faramirza-gdu-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mdwalters/neovide/repo/fedora-%OS_VERSION%/mdwalters-neovide-fedora-%OS_VERSION%.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:
      - autorestic
      - bat
      - difftastic
      - direnv
      - fd-find
      - gh
      - ltrace
      - neovim
      - ripgrep
      - strace
      - tealdeer
      - trash-cli
      - ugrep
      - yq
      # third party pkgs
      - bottom
      - gdu
      - lazygit
      - mullvad-vpn
      - neovide
    optfix:
      - Mullvad VPN

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.bitwarden.desktop
        - com.calibre_ebook.calibre
        - com.discordapp.Discord
        - com.plexamp.Plexamp
        - com.slack.Slack
        - com.valvesoftware.Steam
        - io.github.martchus.syncthingtray
        - it.mijorus.gearlever
        - md.obsidian.Obsidian
        - org.speedcrunch.SpeedCrunch
        - org.telegram.desktop
        - org.wezfurlong.wezterm
        - tv.plex.PlexDesktop
      remove:

  - type: chezmoi
    repository: https://github.com/yacoob/dotfiles
    all-users: false
    file-conflict-policy: skip
    disable-update: true

  - type: signing
