# A runner for https://github.com/nektos/act that contains all tools used by the build workflow
# vim: ft=dockerfile

FROM catthehacker/ubuntu:act-latest@sha256:01991645805fd6fff768097e03b3ab6dcc62ddddc9426206bad6068719dbb63f

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
    skopeo \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
