name: 📜 Build a new image
on:
  workflow_call:
    inputs:
      recipe:
        description: Recipe file to use
        required: true
        type: string
    secrets:
      SIGNING_SECRET:
        required: true

concurrency:
  group: ${{ inputs.recipe }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build a custom image via ${{ inputs.recipe }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      EGET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@4d8b4df657ec923574611eec6fd7e959416c47f0 # v1.8
        with:
          recipe: ${{ inputs.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          rechunk: true
