name: ⚒️ Build a new yaurora image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "recipes/yaucore.yaml"
      - "files/scripts/*-yaucore.sh"
      - "files/system-yaucore/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "recipes/yaucore.yaml"
      - "files/scripts/*-yaucore.sh"
      - "files/system-yaucore/**"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build a new yaurora image
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    uses: ./.github/workflows/build.yaml
    with:
      recipe: yaurora.yaml
