name: ⚒️ Build a new yaucore image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "recipes/yaurora.yaml"
      - "files/scripts/*-yaurora.sh"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "recipes/yaurora.yaml"
      - "files/scripts/*-yaurora.sh"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build a new yaucore image
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    uses: ./.github/workflows/build.yaml
    with:
      recipe: yaucore.yaml
