name: ⚒️ Build a new yaurora image
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yaml"
      - ".github/workflows/build-yaurora.yaml"
      - "files/scripts/base/**"
      - "files/scripts/yaurora/**"
      - "files/system/**"
      - "recipes/base/**"
      - "recipes/yaurora.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build.yaml"
      - ".github/workflows/build-yaurora.yaml"
      - "files/scripts/base/**"
      - "files/scripts/yaurora/**"
      - "files/system/**"
      - "recipes/base/**"
      - "recipes/yaurora.yaml"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build a new yaurora image
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    uses: ./.github/workflows/build.yaml
    with:
      recipe: yaurora.yaml
