name: ⚒️ Build a new yaucore image
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yaml"
      - ".github/workflows/build-yaucore.yaml"
      - "files/scripts/base/**"
      - "files/scripts/yaucore/**"
      - "files/system/**"
      - "recipes/base/**"
      - "recipes/yaucore.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build.yaml"
      - ".github/workflows/build-yaucore.yaml"
      - "files/scripts/base/**"
      - "files/scripts/yaucore/**"
      - "files/system/**"
      - "recipes/base/**"
      - "recipes/yaucore.yaml"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build a new yaucore image
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    uses: ./.github/workflows/build.yaml
    with:
      recipe: yaucore.yaml
